server:
  port: 8888 # 端口的配置
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 106.54.234.175:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: trade-service
          uri: lb://trade-service
          predicates:
              - Path=/orders/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/addresses/**,/users/**
  main:
    web-application-type: reactive  # 为了是减少代码量的修改（不建议这样使用）